version: "3.8"
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    image: project3a_app_image_flask
    container_name: flask_project3a
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
